- name: reload systemd
  command: systemctl daemon-reload

- name: stop {{container_names}}
  docker: image="{{image_name}}" name="{{item}}" state=stopped
  with_items: container_names

# Jenkins takes a while to remove slaves. If containers are started immediately, they will have names
#.containing ip -address of the host in them. ugly :(
- name: wait for containers to be removed on Jenkins side
  command: curl -s -w %{http_code} {{ jenkins_master }}/computer/{{ansible_hostname}}-{{item}}/api/json -o /dev/null
  register: result
  tags: check
  until: result.stdout.find("404") != -1
  retries: 10
  delay: 5
  with_items: container_names

- name: remove {{container_names}}
  docker: name="{{item}}" state=absent image="{{image_name}}"
  with_items: container_names

- name: create containers {{container_names}} with image {{image_name}}
  docker: image="{{image_name}}" name="{{item}}" hostname="{{item}}" memory_limit=4096MB state=present command="\"-name {{ansible_hostname}}-{{item}}\"" volumes="/data/builders/{{item}}:/workspace"
  with_items: container_names
